# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'style/wake.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(800, 484)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(50, 50))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        Form.setFont(font)
        icon = QtGui.QIcon.fromTheme(":/icons/wakeboarding.png")
        Form.setWindowIcon(icon)
        Form.setWindowOpacity(1.0)
        Form.setStyleSheet("#Form { background: rgba(32, 80, 96, 100); \n"
"background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0, y2:0, stop:0 rgba(91, 204, 233, 100), stop:1 rgba(32, 80, 96, 100));\n"
"\n"
"}\n"
"\n"
"\n"
"#topPanel { background-color: qlineargradient(spread:reflect, x1:0.5, y1:0, x2:0, y2:0, stop:0 rgba(91, 204, 233, 100), stop:1 rgba(32, 80, 96, 100));\n"
"}\n"
"\n"
"#tabControl, #tabSettings,#tabMeasurements, #tab_4 {\n"
"background: rgba(32, 80, 96, 100); \n"
"background-image: url(:/images/logo_new.png) repeat-y;\n"
"background-repeat: no-repeat ;\n"
"background-position: center;\n"
"}\n"
"\n"
"#tabWakePark, #tabApplication,#tabComPort,#tabControlWake, #tabModbus, #tabApi{\n"
"background: rgba(32, 80, 96, 100); \n"
"}\n"
"\n"
"\n"
"\n"
"#buttonForm\n"
"{\n"
"    background: rgba(0, 0, 0, 80);\n"
"    border-radius: 8px;\n"
"    border: 1px solid; \n"
"    border-radius:30px;\n"
"}\n"
"#buttonForm_2\n"
"{\n"
"    background: rgba(0, 0, 0, 80);\n"
"    border-radius: 8px;\n"
"    border: 1px solid; \n"
"    border-radius:30px;\n"
"}\n"
"QLabel { color: white; }\n"
"QLineEdit { border-radius: 3px; }\n"
"\n"
"QPushButton\n"
"{\n"
"  color: white;\n"
"  background-color: #27a9e3;\n"
"\n"
"  background-color: qlineargradient(spread:pad, x1:0.469, y1:0, x2:0.503, y2:1, stop:0 rgba(39, 169, 227, 255), stop:1 rgba(51, 93, 112, 255));\n"
"  border-width: 0px;\n"
"  border-radius: 3px;\n"
"}:active\n"
"\n"
"QPushButton:hover { \n"
"background-color: #66c011; \n"
"background-color:qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 rgba(35, 112, 61, 255), stop:0.542289 rgba(105, 170, 127, 255), stop:1 rgba(35, 112, 61, 255)); \n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topPanel = QtWidgets.QWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topPanel.sizePolicy().hasHeightForWidth())
        self.topPanel.setSizePolicy(sizePolicy)
        self.topPanel.setMinimumSize(QtCore.QSize(0, 0))
        self.topPanel.setStyleSheet("")
        self.topPanel.setObjectName("topPanel")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.topPanel)
        self.horizontalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.currentDateTime = QtWidgets.QLabel(self.topPanel)
        self.currentDateTime.setObjectName("currentDateTime")
        self.horizontalLayout_3.addWidget(self.currentDateTime)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.lcdNumber = QtWidgets.QLCDNumber(self.topPanel)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setDigitCount(3)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout_3.addWidget(self.lcdNumber)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.lcdTimer = QtWidgets.QLCDNumber(self.topPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdTimer.sizePolicy().hasHeightForWidth())
        self.lcdTimer.setSizePolicy(sizePolicy)
        self.lcdTimer.setMinimumSize(QtCore.QSize(50, 50))
        self.lcdTimer.setLineWidth(0)
        self.lcdTimer.setMidLineWidth(0)
        self.lcdTimer.setDigitCount(3)
        self.lcdTimer.setObjectName("lcdTimer")
        self.horizontalLayout_3.addWidget(self.lcdTimer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.restartButton = QtWidgets.QPushButton(self.topPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restartButton.sizePolicy().hasHeightForWidth())
        self.restartButton.setSizePolicy(sizePolicy)
        self.restartButton.setMinimumSize(QtCore.QSize(40, 40))
        self.restartButton.setText("")
        self.restartButton.setObjectName("restartButton")
        self.horizontalLayout_3.addWidget(self.restartButton)
        self.shutdownButton = QtWidgets.QPushButton(self.topPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shutdownButton.sizePolicy().hasHeightForWidth())
        self.shutdownButton.setSizePolicy(sizePolicy)
        self.shutdownButton.setMinimumSize(QtCore.QSize(40, 40))
        self.shutdownButton.setStyleSheet("")
        self.shutdownButton.setText("")
        self.shutdownButton.setObjectName("shutdownButton")
        self.horizontalLayout_3.addWidget(self.shutdownButton)
        self.verticalLayout_2.addWidget(self.topPanel)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid black;\n"
"    background: white;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:top {\n"
"    top: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:bottom {\n"
"    bottom: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:left {\n"
"    right: 1px;\n"
"}\n"
"\n"
"QTabWidget::tab-bar:right {\n"
"    left: 1px;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border: 1px solid rgb(49, 85, 97);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(spread:reflect, x1:0, y1:0.523, x2:1, y2:0.5625, stop:0 rgba(0, 255, 0, 100), stop:0.480226 rgba(170, 255, 50, 100), stop:1 rgba(0, 255, 0, 100));\n"
"color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(spread:reflect, x1:0.478, y1:0, x2:0.472, y2:1, stop:0 rgba(51, 93, 112, 255), stop:0.99435 rgba(39, 169, 227, 255));\n"
"\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QTabBar::tab:!selected:hover {\n"
"    background:qlineargradient(spread:reflect, x1:0, y1:0.523, x2:1, y2:0.5625, stop:0 rgba(0, 255, 0, 150), stop:0.480226 rgba(170, 255, 50, 100), stop:1 rgba(0, 255, 0, 150));\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected {\n"
"    margin-top: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected {\n"
"    margin-bottom: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QTabBar::tab:bottom {\n"
"    min-width: 8ex;\n"
"    margin-right: -1px;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    border-bottom-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected {\n"
"    border-top-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:top:last, QTabBar::tab:bottom:last,\n"
"QTabBar::tab:top:only-one, QTabBar::tab:bottom:only-one {\n"
"    margin-right: 0;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected {\n"
"    margin-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected {\n"
"    margin-left: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QTabBar::tab:right {\n"
"    min-height: 8ex;\n"
"    margin-bottom: -1px;\n"
"    padding: 10px 5px 10px 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected {\n"
"    border-left-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected {\n"
"    border-right-color: none;\n"
"}\n"
"\n"
"QTabBar::tab:left:last, QTabBar::tab:right:last,\n"
"QTabBar::tab:left:only-one, QTabBar::tab:right:only-one {\n"
"    margin-bottom: 0;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabControl = QtWidgets.QWidget()
        self.tabControl.setObjectName("tabControl")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabControl)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.tabControl)
        self.widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setContentsMargins(10, -1, 0, -1)
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_1 = QtWidgets.QLabel(self.widget)
        self.Label_1.setObjectName("Label_1")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_1)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(56)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setPageStep(0)
        self.horizontalSlider.setProperty("value", 20)
        self.horizontalSlider.setSliderPosition(20)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(0)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider)
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setReadOnly(False)
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(56)
        self.spinBox.setProperty("value", 20)
        self.spinBox.setObjectName("spinBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.spinBox)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(350, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.widget)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setContentsMargins(0, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonForm_2 = QtWidgets.QWidget(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonForm_2.sizePolicy().hasHeightForWidth())
        self.buttonForm_2.setSizePolicy(sizePolicy)
        self.buttonForm_2.setMinimumSize(QtCore.QSize(780, 90))
        self.buttonForm_2.setMaximumSize(QtCore.QSize(150, 150))
        self.buttonForm_2.setObjectName("buttonForm_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.buttonForm_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.pushButtonRevers = QtWidgets.QPushButton(self.buttonForm_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRevers.sizePolicy().hasHeightForWidth())
        self.pushButtonRevers.setSizePolicy(sizePolicy)
        self.pushButtonRevers.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButtonRevers.setObjectName("pushButtonRevers")
        self.horizontalLayout_9.addWidget(self.pushButtonRevers)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.pushButtonStart = QtWidgets.QPushButton(self.buttonForm_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStart.sizePolicy().hasHeightForWidth())
        self.pushButtonStart.setSizePolicy(sizePolicy)
        self.pushButtonStart.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.horizontalLayout_9.addWidget(self.pushButtonStart)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.pushButtonHome = QtWidgets.QPushButton(self.buttonForm_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonHome.sizePolicy().hasHeightForWidth())
        self.pushButtonHome.setSizePolicy(sizePolicy)
        self.pushButtonHome.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButtonHome.setObjectName("pushButtonHome")
        self.horizontalLayout_9.addWidget(self.pushButtonHome)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.pushButtonStartTimer = QtWidgets.QPushButton(self.buttonForm_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartTimer.sizePolicy().hasHeightForWidth())
        self.pushButtonStartTimer.setSizePolicy(sizePolicy)
        self.pushButtonStartTimer.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButtonStartTimer.setObjectName("pushButtonStartTimer")
        self.horizontalLayout_9.addWidget(self.pushButtonStartTimer)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4.addWidget(self.buttonForm_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem11 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem11)
        spacerItem12 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem13)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.buttonForm = QtWidgets.QWidget(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonForm.sizePolicy().hasHeightForWidth())
        self.buttonForm.setSizePolicy(sizePolicy)
        self.buttonForm.setMinimumSize(QtCore.QSize(600, 100))
        self.buttonForm.setStyleSheet("")
        self.buttonForm.setObjectName("buttonForm")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.buttonForm)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButtonBackward = QtWidgets.QPushButton(self.buttonForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBackward.sizePolicy().hasHeightForWidth())
        self.pushButtonBackward.setSizePolicy(sizePolicy)
        self.pushButtonBackward.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButtonBackward.setObjectName("pushButtonBackward")
        self.horizontalLayout_7.addWidget(self.pushButtonBackward)
        self.pushButtonStop = QtWidgets.QPushButton(self.buttonForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStop.sizePolicy().hasHeightForWidth())
        self.pushButtonStop.setSizePolicy(sizePolicy)
        self.pushButtonStop.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.horizontalLayout_7.addWidget(self.pushButtonStop)
        self.pushButtonForward = QtWidgets.QPushButton(self.buttonForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonForward.sizePolicy().hasHeightForWidth())
        self.pushButtonForward.setSizePolicy(sizePolicy)
        self.pushButtonForward.setMinimumSize(QtCore.QSize(150, 75))
        self.pushButtonForward.setMouseTracking(False)
        self.pushButtonForward.setObjectName("pushButtonForward")
        self.horizontalLayout_7.addWidget(self.pushButtonForward)
        self.horizontalLayout_5.addWidget(self.buttonForm)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(10, -1, -1, 0)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lb = QtWidgets.QLabel(self.tabControl)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb.sizePolicy().hasHeightForWidth())
        self.lb.setSizePolicy(sizePolicy)
        self.lb.setMinimumSize(QtCore.QSize(120, 0))
        self.lb.setObjectName("lb")
        self.verticalLayout_8.addWidget(self.lb)
        self.errorGet = QtWidgets.QLabel(self.tabControl)
        self.errorGet.setText("")
        self.errorGet.setObjectName("errorGet")
        self.verticalLayout_8.addWidget(self.errorGet)
        self.verticalLayout_4.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tabControl, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tabMeasurements = QtWidgets.QWidget()
        self.tabMeasurements.setObjectName("tabMeasurements")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.tabMeasurements)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.line_15 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.verticalLayout_25.addWidget(self.line_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lbFrequency = QtWidgets.QLabel(self.tabMeasurements)
        self.lbFrequency.setAlignment(QtCore.Qt.AlignCenter)
        self.lbFrequency.setWordWrap(False)
        self.lbFrequency.setObjectName("lbFrequency")
        self.verticalLayout_14.addWidget(self.lbFrequency)
        self.lbSetFrequency = QtWidgets.QLabel(self.tabMeasurements)
        self.lbSetFrequency.setAlignment(QtCore.Qt.AlignCenter)
        self.lbSetFrequency.setObjectName("lbSetFrequency")
        self.verticalLayout_14.addWidget(self.lbSetFrequency)
        self.horizontalLayout_16.addLayout(self.verticalLayout_14)
        self.line_3 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_16.addWidget(self.line_3)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lbOFrequency = QtWidgets.QLabel(self.tabMeasurements)
        self.lbOFrequency.setAlignment(QtCore.Qt.AlignCenter)
        self.lbOFrequency.setObjectName("lbOFrequency")
        self.verticalLayout_15.addWidget(self.lbOFrequency)
        self.lbOutputFrequency = QtWidgets.QLabel(self.tabMeasurements)
        self.lbOutputFrequency.setAlignment(QtCore.Qt.AlignCenter)
        self.lbOutputFrequency.setObjectName("lbOutputFrequency")
        self.verticalLayout_15.addWidget(self.lbOutputFrequency)
        self.horizontalLayout_16.addLayout(self.verticalLayout_15)
        self.line_4 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_16.addWidget(self.line_4)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lbRSpeed = QtWidgets.QLabel(self.tabMeasurements)
        self.lbRSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lbRSpeed.setObjectName("lbRSpeed")
        self.verticalLayout_16.addWidget(self.lbRSpeed)
        self.lbRotationalSpeed = QtWidgets.QLabel(self.tabMeasurements)
        self.lbRotationalSpeed.setAlignment(QtCore.Qt.AlignCenter)
        self.lbRotationalSpeed.setObjectName("lbRotationalSpeed")
        self.verticalLayout_16.addWidget(self.lbRotationalSpeed)
        self.horizontalLayout_16.addLayout(self.verticalLayout_16)
        self.line_5 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_16.addWidget(self.line_5)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lbOHCounter = QtWidgets.QLabel(self.tabMeasurements)
        self.lbOHCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.lbOHCounter.setWordWrap(True)
        self.lbOHCounter.setIndent(0)
        self.lbOHCounter.setOpenExternalLinks(False)
        self.lbOHCounter.setObjectName("lbOHCounter")
        self.verticalLayout_19.addWidget(self.lbOHCounter)
        self.lbOperatingHoursCounter = QtWidgets.QLabel(self.tabMeasurements)
        self.lbOperatingHoursCounter.setAlignment(QtCore.Qt.AlignCenter)
        self.lbOperatingHoursCounter.setObjectName("lbOperatingHoursCounter")
        self.verticalLayout_19.addWidget(self.lbOperatingHoursCounter)
        self.horizontalLayout_16.addLayout(self.verticalLayout_19)
        self.verticalLayout_25.addLayout(self.horizontalLayout_16)
        self.line = QtWidgets.QFrame(self.tabMeasurements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_25.addWidget(self.line)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.lbFeedbakValue = QtWidgets.QLabel(self.tabMeasurements)
        self.lbFeedbakValue.setAlignment(QtCore.Qt.AlignCenter)
        self.lbFeedbakValue.setWordWrap(True)
        self.lbFeedbakValue.setIndent(0)
        self.lbFeedbakValue.setOpenExternalLinks(False)
        self.lbFeedbakValue.setObjectName("lbFeedbakValue")
        self.verticalLayout_22.addWidget(self.lbFeedbakValue)
        self.lbFeedbackPidMode = QtWidgets.QLabel(self.tabMeasurements)
        self.lbFeedbackPidMode.setAlignment(QtCore.Qt.AlignCenter)
        self.lbFeedbackPidMode.setObjectName("lbFeedbackPidMode")
        self.verticalLayout_22.addWidget(self.lbFeedbackPidMode)
        self.horizontalLayout_17.addLayout(self.verticalLayout_22)
        self.line_6 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_17.addWidget(self.line_6)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lbVoltage = QtWidgets.QLabel(self.tabMeasurements)
        self.lbVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbVoltage.setWordWrap(True)
        self.lbVoltage.setObjectName("lbVoltage")
        self.verticalLayout_18.addWidget(self.lbVoltage)
        self.lbDCBusVoltage = QtWidgets.QLabel(self.tabMeasurements)
        self.lbDCBusVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbDCBusVoltage.setObjectName("lbDCBusVoltage")
        self.verticalLayout_18.addWidget(self.lbDCBusVoltage)
        self.horizontalLayout_17.addLayout(self.verticalLayout_18)
        self.line_7 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_17.addWidget(self.line_7)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lbOCurrent = QtWidgets.QLabel(self.tabMeasurements)
        self.lbOCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.lbOCurrent.setObjectName("lbOCurrent")
        self.verticalLayout_17.addWidget(self.lbOCurrent)
        self.lbOutputCurrent = QtWidgets.QLabel(self.tabMeasurements)
        self.lbOutputCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.lbOutputCurrent.setObjectName("lbOutputCurrent")
        self.verticalLayout_17.addWidget(self.lbOutputCurrent)
        self.horizontalLayout_17.addLayout(self.verticalLayout_17)
        self.verticalLayout_25.addLayout(self.horizontalLayout_17)
        self.line_2 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_25.addWidget(self.line_2)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.lbError1 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbError1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbError1.setWordWrap(True)
        self.lbError1.setIndent(0)
        self.lbError1.setOpenExternalLinks(False)
        self.lbError1.setObjectName("lbError1")
        self.verticalLayout_20.addWidget(self.lbError1)
        self.lbErrorRecord1 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorRecord1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorRecord1.setObjectName("lbErrorRecord1")
        self.verticalLayout_20.addWidget(self.lbErrorRecord1)
        self.horizontalLayout_18.addLayout(self.verticalLayout_20)
        self.line_8 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_18.addWidget(self.line_8)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.lbError2 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbError2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbError2.setWordWrap(True)
        self.lbError2.setIndent(0)
        self.lbError2.setOpenExternalLinks(False)
        self.lbError2.setObjectName("lbError2")
        self.verticalLayout_21.addWidget(self.lbError2)
        self.lbErrorRecord2 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorRecord2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorRecord2.setObjectName("lbErrorRecord2")
        self.verticalLayout_21.addWidget(self.lbErrorRecord2)
        self.horizontalLayout_18.addLayout(self.verticalLayout_21)
        self.line_9 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.horizontalLayout_18.addWidget(self.line_9)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.lbError3 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbError3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbError3.setWordWrap(True)
        self.lbError3.setIndent(0)
        self.lbError3.setOpenExternalLinks(False)
        self.lbError3.setObjectName("lbError3")
        self.verticalLayout_23.addWidget(self.lbError3)
        self.lbErrorRecord3 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorRecord3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorRecord3.setObjectName("lbErrorRecord3")
        self.verticalLayout_23.addWidget(self.lbErrorRecord3)
        self.horizontalLayout_18.addLayout(self.verticalLayout_23)
        self.line_10 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.horizontalLayout_18.addWidget(self.line_10)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.lbError4 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbError4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbError4.setWordWrap(True)
        self.lbError4.setIndent(0)
        self.lbError4.setOpenExternalLinks(False)
        self.lbError4.setObjectName("lbError4")
        self.verticalLayout_24.addWidget(self.lbError4)
        self.lbErrorRecord4 = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorRecord4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorRecord4.setObjectName("lbErrorRecord4")
        self.verticalLayout_24.addWidget(self.lbErrorRecord4)
        self.horizontalLayout_18.addLayout(self.verticalLayout_24)
        self.verticalLayout_25.addLayout(self.horizontalLayout_18)
        self.line_11 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.verticalLayout_25.addWidget(self.line_11)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_19.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_8 = QtWidgets.QLabel(self.tabMeasurements)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_29.addWidget(self.label_8)
        self.lbErrorFreq = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorFreq.setObjectName("lbErrorFreq")
        self.verticalLayout_29.addWidget(self.lbErrorFreq)
        self.horizontalLayout_19.addLayout(self.verticalLayout_29)
        self.line_12 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_19.addWidget(self.line_12)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_31.setSpacing(6)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_9 = QtWidgets.QLabel(self.tabMeasurements)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_31.addWidget(self.label_9)
        self.lbErrorOutFreq = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorOutFreq.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorOutFreq.setObjectName("lbErrorOutFreq")
        self.verticalLayout_31.addWidget(self.lbErrorOutFreq)
        self.horizontalLayout_19.addLayout(self.verticalLayout_31)
        self.line_13 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_19.addWidget(self.line_13)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_11 = QtWidgets.QLabel(self.tabMeasurements)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_32.addWidget(self.label_11)
        self.lbErrorCurrent = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorCurrent.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorCurrent.setObjectName("lbErrorCurrent")
        self.verticalLayout_32.addWidget(self.lbErrorCurrent)
        self.horizontalLayout_19.addLayout(self.verticalLayout_32)
        self.line_14 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_19.addWidget(self.line_14)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setContentsMargins(-1, -1, 20, -1)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_14 = QtWidgets.QLabel(self.tabMeasurements)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_33.addWidget(self.label_14)
        self.lbErrorOutVoltage = QtWidgets.QLabel(self.tabMeasurements)
        self.lbErrorOutVoltage.setAlignment(QtCore.Qt.AlignCenter)
        self.lbErrorOutVoltage.setObjectName("lbErrorOutVoltage")
        self.verticalLayout_33.addWidget(self.lbErrorOutVoltage)
        self.horizontalLayout_19.addLayout(self.verticalLayout_33)
        self.verticalLayout_25.addLayout(self.horizontalLayout_19)
        self.line_16 = QtWidgets.QFrame(self.tabMeasurements)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.verticalLayout_25.addWidget(self.line_16)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.tabMeasurements)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUpdate.sizePolicy().hasHeightForWidth())
        self.pushButtonUpdate.setSizePolicy(sizePolicy)
        self.pushButtonUpdate.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.verticalLayout_25.addWidget(self.pushButtonUpdate, 0, QtCore.Qt.AlignHCenter)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem15)
        self.tabWidget.addTab(self.tabMeasurements, "")
        self.tabSettings = QtWidgets.QWidget()
        self.tabSettings.setObjectName("tabSettings")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tabSettings)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.addSettings = QtWidgets.QTabWidget(self.tabSettings)
        self.addSettings.setTabPosition(QtWidgets.QTabWidget.South)
        self.addSettings.setUsesScrollButtons(True)
        self.addSettings.setDocumentMode(True)
        self.addSettings.setTabsClosable(False)
        self.addSettings.setMovable(False)
        self.addSettings.setTabBarAutoHide(True)
        self.addSettings.setObjectName("addSettings")
        self.tabWakePark = QtWidgets.QWidget()
        self.tabWakePark.setObjectName("tabWakePark")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tabWakePark)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 302, 140))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.timeEdit = QtWidgets.QTimeEdit(self.verticalLayoutWidget_2)
        self.timeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 10, 0)))
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setObjectName("timeEdit")
        self.horizontalLayout_12.addWidget(self.timeEdit)
        self.pushButtonSaveSetTime = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSaveSetTime.sizePolicy().hasHeightForWidth())
        self.pushButtonSaveSetTime.setSizePolicy(sizePolicy)
        self.pushButtonSaveSetTime.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButtonSaveSetTime.setObjectName("pushButtonSaveSetTime")
        self.horizontalLayout_12.addWidget(self.pushButtonSaveSetTime)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        spacerItem16 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem16)
        self.addSettings.addTab(self.tabWakePark, "")
        self.tabApplication = QtWidgets.QWidget()
        self.tabApplication.setObjectName("tabApplication")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tabApplication)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.requestPassword = QtWidgets.QCheckBox(self.tabApplication)
        self.requestPassword.setStyleSheet("\n"
"color: white; ")
        self.requestPassword.setCheckable(True)
        self.requestPassword.setChecked(True)
        self.requestPassword.setTristate(False)
        self.requestPassword.setObjectName("requestPassword")
        self.horizontalLayout_10.addWidget(self.requestPassword, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.label = QtWidgets.QLabel(self.tabApplication)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.passwordEdit = QtWidgets.QLineEdit(self.tabApplication)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passwordEdit.sizePolicy().hasHeightForWidth())
        self.passwordEdit.setSizePolicy(sizePolicy)
        self.passwordEdit.setMinimumSize(QtCore.QSize(100, 20))
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout.addWidget(self.passwordEdit)
        self.pushButtonSavePassword = QtWidgets.QPushButton(self.tabApplication)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSavePassword.sizePolicy().hasHeightForWidth())
        self.pushButtonSavePassword.setSizePolicy(sizePolicy)
        self.pushButtonSavePassword.setMinimumSize(QtCore.QSize(100, 20))
        self.pushButtonSavePassword.setObjectName("pushButtonSavePassword")
        self.horizontalLayout.addWidget(self.pushButtonSavePassword)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem17 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem17)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_9.addItem(spacerItem18)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_13.addLayout(self.horizontalLayout_11)
        spacerItem19 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem19)
        self.verticalLayout_9.addLayout(self.horizontalLayout_13)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem20)
        self.addSettings.addTab(self.tabApplication, "")
        self.tabControlWake = QtWidgets.QWidget()
        self.tabControlWake.setObjectName("tabControlWake")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.tabControlWake)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.comboBoxControl = QtWidgets.QComboBox(self.tabControlWake)
        self.comboBoxControl.setObjectName("comboBoxControl")
        self.verticalLayout_12.addWidget(self.comboBoxControl)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setSpacing(7)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.pushButtonRecord = QtWidgets.QPushButton(self.tabControlWake)
        self.pushButtonRecord.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonRecord.setObjectName("pushButtonRecord")
        self.verticalLayout_28.addWidget(self.pushButtonRecord)
        self.recordButtonStart = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonStart.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonStart.setObjectName("recordButtonStart")
        self.verticalLayout_28.addWidget(self.recordButtonStart)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setSpacing(6)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.recordButtonForward = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonForward.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonForward.setStyleSheet("")
        self.recordButtonForward.setObjectName("recordButtonForward")
        self.verticalLayout_30.addWidget(self.recordButtonForward)
        self.recordButtonStop = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonStop.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonStop.setObjectName("recordButtonStop")
        self.verticalLayout_30.addWidget(self.recordButtonStop)
        self.recordButtonSpeedDown = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonSpeedDown.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonSpeedDown.setObjectName("recordButtonSpeedDown")
        self.verticalLayout_30.addWidget(self.recordButtonSpeedDown)
        self.recordButtonStartTimer = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonStartTimer.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonStartTimer.setObjectName("recordButtonStartTimer")
        self.verticalLayout_30.addWidget(self.recordButtonStartTimer)
        self.horizontalLayout_20.addLayout(self.verticalLayout_30)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setSpacing(6)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.recordButtonBackward = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonBackward.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonBackward.setObjectName("recordButtonBackward")
        self.verticalLayout_34.addWidget(self.recordButtonBackward)
        self.recordButtonHome = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonHome.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonHome.setObjectName("recordButtonHome")
        self.verticalLayout_34.addWidget(self.recordButtonHome)
        self.recordButtonSpeedUp = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonSpeedUp.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonSpeedUp.setObjectName("recordButtonSpeedUp")
        self.verticalLayout_34.addWidget(self.recordButtonSpeedUp)
        self.recordButtonRevers = QtWidgets.QPushButton(self.tabControlWake)
        self.recordButtonRevers.setMinimumSize(QtCore.QSize(0, 25))
        self.recordButtonRevers.setObjectName("recordButtonRevers")
        self.verticalLayout_34.addWidget(self.recordButtonRevers)
        self.horizontalLayout_20.addLayout(self.verticalLayout_34)
        self.verticalLayout_28.addLayout(self.horizontalLayout_20)
        self.verticalLayout_12.addLayout(self.verticalLayout_28)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem21)
        self.horizontalLayout_14.addLayout(self.verticalLayout_12)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_14)
        spacerItem22 = QtWidgets.QSpacerItem(500, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem22)
        self.addSettings.addTab(self.tabControlWake, "")
        self.tabModbus = QtWidgets.QWidget()
        self.tabModbus.setObjectName("tabModbus")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabModbus)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 451, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalWidget_13 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_13.sizePolicy().hasHeightForWidth())
        self.verticalWidget_13.setSizePolicy(sizePolicy)
        self.verticalWidget_13.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalWidget_13.setObjectName("verticalWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalWidget_13)
        self.verticalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_5 = QtWidgets.QLabel(self.verticalWidget_13)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_13.addWidget(self.label_5)
        self.editParameterAdress = QtWidgets.QLineEdit(self.verticalWidget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editParameterAdress.sizePolicy().hasHeightForWidth())
        self.editParameterAdress.setSizePolicy(sizePolicy)
        self.editParameterAdress.setMinimumSize(QtCore.QSize(20, 20))
        self.editParameterAdress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.editParameterAdress.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.editParameterAdress.setObjectName("editParameterAdress")
        self.verticalLayout_13.addWidget(self.editParameterAdress)
        self.horizontalLayout_15.addWidget(self.verticalWidget_13)
        self.verticalWidget_14 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget_14.sizePolicy().hasHeightForWidth())
        self.verticalWidget_14.setSizePolicy(sizePolicy)
        self.verticalWidget_14.setMinimumSize(QtCore.QSize(0, 0))
        self.verticalWidget_14.setObjectName("verticalWidget_14")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalWidget_14)
        self.verticalLayout_26.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_7 = QtWidgets.QLabel(self.verticalWidget_14)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_26.addWidget(self.label_7)
        self.editValue = QtWidgets.QLineEdit(self.verticalWidget_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editValue.sizePolicy().hasHeightForWidth())
        self.editValue.setSizePolicy(sizePolicy)
        self.editValue.setMinimumSize(QtCore.QSize(20, 20))
        self.editValue.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.editValue.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.editValue.setObjectName("editValue")
        self.verticalLayout_26.addWidget(self.editValue)
        self.horizontalLayout_15.addWidget(self.verticalWidget_14)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setContentsMargins(0, 20, -1, -1)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.pushButtonSubmit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(25)
        sizePolicy.setHeightForWidth(self.pushButtonSubmit.sizePolicy().hasHeightForWidth())
        self.pushButtonSubmit.setSizePolicy(sizePolicy)
        self.pushButtonSubmit.setMinimumSize(QtCore.QSize(25, 20))
        self.pushButtonSubmit.setMaximumSize(QtCore.QSize(100, 25))
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.verticalLayout_27.addWidget(self.pushButtonSubmit)
        self.horizontalLayout_15.addLayout(self.verticalLayout_27)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabModbus)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 90, 321, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.getParameterAdress = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.getParameterAdress.setText("")
        self.getParameterAdress.setObjectName("getParameterAdress")
        self.horizontalLayout_21.addWidget(self.getParameterAdress)
        self.getParameterValue = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.getParameterValue.setText("")
        self.getParameterValue.setObjectName("getParameterValue")
        self.horizontalLayout_21.addWidget(self.getParameterValue)
        self.layoutWidget = QtWidgets.QWidget(self.tabModbus)
        self.layoutWidget.setGeometry(QtCore.QRect(460, 10, 331, 214))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.Port = QtWidgets.QComboBox(self.layoutWidget)
        self.Port.setObjectName("Port")
        self.verticalLayout_3.addWidget(self.Port)
        self.verticalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem23 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem23)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.Speed = QtWidgets.QComboBox(self.layoutWidget)
        self.Speed.setObjectName("Speed")
        self.verticalLayout_10.addWidget(self.Speed)
        spacerItem24 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_10.addItem(spacerItem24)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_10.addWidget(self.label_19)
        self.Adress = QtWidgets.QComboBox(self.layoutWidget)
        self.Adress.setObjectName("Adress")
        self.verticalLayout_10.addWidget(self.Adress)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.addSettings.addTab(self.tabModbus, "")
        self.tabApi = QtWidgets.QWidget()
        self.tabApi.setObjectName("tabApi")
        self.ipEdit = QtWidgets.QLineEdit(self.tabApi)
        self.ipEdit.setGeometry(QtCore.QRect(40, 50, 113, 25))
        self.ipEdit.setObjectName("ipEdit")
        self.portEdit = QtWidgets.QLineEdit(self.tabApi)
        self.portEdit.setGeometry(QtCore.QRect(170, 50, 113, 25))
        self.portEdit.setObjectName("portEdit")
        self.pushButtonApiSave = QtWidgets.QPushButton(self.tabApi)
        self.pushButtonApiSave.setGeometry(QtCore.QRect(300, 50, 89, 25))
        self.pushButtonApiSave.setObjectName("pushButtonApiSave")
        self.label_6 = QtWidgets.QLabel(self.tabApi)
        self.label_6.setGeometry(QtCore.QRect(40, 30, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_10 = QtWidgets.QLabel(self.tabApi)
        self.label_10.setGeometry(QtCore.QRect(170, 30, 67, 17))
        self.label_10.setObjectName("label_10")
        self.pushButtonApiStart = QtWidgets.QPushButton(self.tabApi)
        self.pushButtonApiStart.setGeometry(QtCore.QRect(20, 160, 89, 25))
        self.pushButtonApiStart.setObjectName("pushButtonApiStart")
        self.pushButtonApiStop = QtWidgets.QPushButton(self.tabApi)
        self.pushButtonApiStop.setGeometry(QtCore.QRect(120, 160, 89, 25))
        self.pushButtonApiStop.setObjectName("pushButtonApiStop")
        self.label_12 = QtWidgets.QLabel(self.tabApi)
        self.label_12.setGeometry(QtCore.QRect(30, 230, 67, 17))
        self.label_12.setObjectName("label_12")
        self.labelApiRun = QtWidgets.QLabel(self.tabApi)
        self.labelApiRun.setGeometry(QtCore.QRect(10, 260, 161, 41))
        self.labelApiRun.setText("")
        self.labelApiRun.setObjectName("labelApiRun")
        self.checkApiReq = QtWidgets.QCheckBox(self.tabApi)
        self.checkApiReq.setGeometry(QtCore.QRect(20, 100, 181, 23))
        self.checkApiReq.setObjectName("checkApiReq")
        self.addSettings.addTab(self.tabApi, "")
        self.verticalLayout_7.addWidget(self.addSettings)
        self.tabWidget.addTab(self.tabSettings, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.addSettings.setCurrentIndex(4)
        self.shutdownButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "WakePark"))
        self.currentDateTime.setText(_translate("Form", "Monday, 25-10-2015 3:14 PM"))
        self.Label_1.setText(_translate("Form", "Speed"))
        self.pushButtonRevers.setText(_translate("Form", "Revers"))
        self.pushButtonStart.setText(_translate("Form", "Start"))
        self.pushButtonHome.setText(_translate("Form", "Home"))
        self.pushButtonStartTimer.setText(_translate("Form", "Timer"))
        self.pushButtonBackward.setText(_translate("Form", "Backward"))
        self.pushButtonStop.setText(_translate("Form", "Stop"))
        self.pushButtonForward.setText(_translate("Form", "Forward"))
        self.lb.setText(_translate("Form", "Что нажал: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabControl), _translate("Form", "Управление"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Опытный"))
        self.lbFrequency.setText(_translate("Form", "Заданная частота"))
        self.lbSetFrequency.setText(_translate("Form", "Set"))
        self.lbOFrequency.setText(_translate("Form", "Выходная частота"))
        self.lbOutputFrequency.setText(_translate("Form", "Output"))
        self.lbRSpeed.setText(_translate("Form", "Скорость вращения"))
        self.lbRotationalSpeed.setText(_translate("Form", "Speed"))
        self.lbOHCounter.setText(_translate("Form", "Счетчик часов эксплуатации"))
        self.lbOperatingHoursCounter.setText(_translate("Form", "Counter"))
        self.lbFeedbakValue.setText(_translate("Form", "При использовании PID режима"))
        self.lbFeedbackPidMode.setText(_translate("Form", "Feedback"))
        self.lbVoltage.setText(_translate("Form", "Напряжение на шине постоянного тока"))
        self.lbDCBusVoltage.setText(_translate("Form", "Bus Voltage"))
        self.lbOCurrent.setText(_translate("Form", "Выходной ток"))
        self.lbOutputCurrent.setText(_translate("Form", "Current"))
        self.lbError1.setText(_translate("Form", "Запись об ошибке 1"))
        self.lbErrorRecord1.setText(_translate("Form", "Error1"))
        self.lbError2.setText(_translate("Form", "Запись об ошибке 2"))
        self.lbErrorRecord2.setText(_translate("Form", "Error2"))
        self.lbError3.setText(_translate("Form", "Запись об ошибке 3"))
        self.lbErrorRecord3.setText(_translate("Form", "Error3"))
        self.lbError4.setText(_translate("Form", "Запись об ошибке 4"))
        self.lbErrorRecord4.setText(_translate("Form", "Error4"))
        self.label_8.setText(_translate("Form", "Частота в момент \n"
"последней\n"
"неисправности"))
        self.lbErrorFreq.setText(_translate("Form", "Freq"))
        self.label_9.setText(_translate("Form", "Частота в момент \n"
"последней\n"
"неисправности"))
        self.lbErrorOutFreq.setText(_translate("Form", "OutFreq"))
        self.label_11.setText(_translate("Form", "Ток в момент \n"
"последней \n"
"неисправности"))
        self.lbErrorCurrent.setText(_translate("Form", "OutCurrent"))
        self.label_14.setText(_translate("Form", "Напряжение в момент \n"
"последней \n"
"неисправности"))
        self.lbErrorOutVoltage.setText(_translate("Form", "OutVoltage"))
        self.pushButtonUpdate.setText(_translate("Form", "ОБНОВИТЬ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMeasurements), _translate("Form", "Измерения"))
        self.label_2.setText(_translate("Form", "Длительность сета в мин."))
        self.timeEdit.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.pushButtonSaveSetTime.setText(_translate("Form", "Сохранить"))
        self.addSettings.setTabText(self.addSettings.indexOf(self.tabWakePark), _translate("Form", "WakePark"))
        self.requestPassword.setText(_translate("Form", "Запрашивать Пин-код"))
        self.label.setText(_translate("Form", "Сменить пин код"))
        self.pushButtonSavePassword.setText(_translate("Form", "Сохранить"))
        self.addSettings.setTabText(self.addSettings.indexOf(self.tabApplication), _translate("Form", "Application"))
        self.pushButtonRecord.setText(_translate("Form", "Включить Редактор"))
        self.recordButtonStart.setText(_translate("Form", "Старт"))
        self.recordButtonForward.setText(_translate("Form", "Вперед"))
        self.recordButtonStop.setText(_translate("Form", "Стоп"))
        self.recordButtonSpeedDown.setText(_translate("Form", "Сорость -"))
        self.recordButtonStartTimer.setText(_translate("Form", "Таймер"))
        self.recordButtonBackward.setText(_translate("Form", "Назад"))
        self.recordButtonHome.setText(_translate("Form", "Домой"))
        self.recordButtonSpeedUp.setText(_translate("Form", "Скорость +"))
        self.recordButtonRevers.setText(_translate("Form", "Реверс"))
        self.addSettings.setTabText(self.addSettings.indexOf(self.tabControlWake), _translate("Form", "Control"))
        self.label_5.setText(_translate("Form", "Адресс параметра"))
        self.label_7.setText(_translate("Form", "Значение"))
        self.pushButtonSubmit.setText(_translate("Form", "Отправить"))
        self.label_3.setText(_translate("Form", "Порт"))
        self.label_4.setText(_translate("Form", "Скорость"))
        self.label_19.setText(_translate("Form", "Адрес"))
        self.addSettings.setTabText(self.addSettings.indexOf(self.tabModbus), _translate("Form", "ModBus"))
        self.pushButtonApiSave.setText(_translate("Form", "Сохранить"))
        self.label_6.setText(_translate("Form", "IP"))
        self.label_10.setText(_translate("Form", "Port"))
        self.pushButtonApiStart.setText(_translate("Form", "Запустить"))
        self.pushButtonApiStop.setText(_translate("Form", "Остановить"))
        self.label_12.setText(_translate("Form", "Статус"))
        self.checkApiReq.setText(_translate("Form", "Заупскать при старте"))
        self.addSettings.setTabText(self.addSettings.indexOf(self.tabApi), _translate("Form", "API"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSettings), _translate("Form", "Настройки"))

import source_rc
